var App;
(function (App) {
    "use strict";
    var UrlService = (function () {
        function UrlService() {
            var baseUrl = "";
            //baseUrl = "/ShoppersZone";
            var baseApi = baseUrl + "/api";
            this.BaseUrl = baseUrl;
            this.SigninUrl = baseUrl + "/token";
            this.PermissionUrl = baseApi + "/Permission";
            this.RegisterUrl = baseApi + "/Account/Register";
            this.SideMenuUrl = baseApi + "/SideMenu";
            this.ProfileUrl = baseApi + "/Account/GetUserInfo";
            this.ChangePasswordUrl = baseApi + "/Account/ChangePassword";
            //business
            this.BarcodeImage = baseApi + "/BarcodeImage";
            this.productQuery = baseApi + "/ProductQuery";
            this.ProductQueryBarcode = this.productQuery + "/Barcode";
            this.ProductQueryData = this.productQuery + "/Data";
            this.ProductQueryCount = this.productQuery + "/Count";
            this.ProductQueryReport = this.productQuery + "/Report";
            this.Product = baseApi + "/Product";
            this.SupplierQuery = baseApi + "/SupplierQuery";
            this.Supplier = baseApi + "/Supplier";
            this.SupplierQueryData = this.SupplierQuery + "/Data";
            this.SupplierQueryCount = this.SupplierQuery + "/Count";
            this.SupplierQueryReport = this.SupplierQuery + "/Report";
            this.SupplierHistoryQuery = baseApi + "/SupplierHistoryQuery";
            this.Purchase = baseApi + "/Purchase";
            this.PurchaseQuery = baseApi + "/PurchaseQuery";
            this.PurchaseQueryData = this.PurchaseQuery + "/Data";
            this.PurchaseQueryCount = this.PurchaseQuery + "/Count";
            this.PurchaseQueryReport = this.PurchaseQuery + "/Report";
            this.PurchaseDetail = baseApi + "/PurchaseDetail";
            this.PurchaseDetailQuery = baseApi + "/PurchaseDetailQuery";
            this.Payment = baseApi + "/Payment";
            this.PaymentQuery = baseApi + "/PaymentQuery";
            this.PaymentQueryData = this.PaymentQuery + "/Data";
            this.PaymentQueryCount = this.PaymentQuery + "/Count";
            this.PaymentQueryReport = this.PaymentQuery + "/Report";
            this.Dropdown = baseApi + "/Dropdown";
            this.Sale = baseApi + "/Sale";
            this.saleQuery = baseApi + "/SaleQuery";
            this.SaleQueryData = this.saleQuery + "/Data";
            this.SaleQueryCount = this.saleQuery + "/Count";
            this.SaleQueryReport = this.saleQuery + "/Report";
            this.SaleDetail = baseApi + "/SaleDetail";
            this.SaleDetailQuery = baseApi + "/SaleDetailQuery";
            this.Bookmark = baseApi + "/Bookmark";
            this.BookmarkQuery = baseApi + "/BookmarkQuery";
            this.BookmarkQueryData = this.BookmarkQuery + "/Data";
            this.BookmarkQueryCount = this.BookmarkQuery + "/Count";
            this.ProductBookmark = baseApi + "/ProductBookmark";
            this.ProductBookmarkQuery = baseApi + "/ProductBookmarkQuery";
            this.ProductBookmarkQueryData = this.ProductBookmarkQuery + "/Data";
            this.ProductBookmarkQueryCount = this.ProductBookmarkQuery + "/Count";
            this.StockQuery = baseApi + "/StockQuery";
            this.StockQueryData = this.StockQuery + "/Data";
            this.StockQueryCount = this.StockQuery + "/Count";
            this.CustomerQuery = baseApi + "/CustomerQuery";
            this.Customer = baseApi + "/Customer";
            this.CustomerQueryBarcode = this.CustomerQuery + "/Barcode";
            this.CustomerQueryData = this.CustomerQuery + "/Data";
            this.CustomerQueryCount = this.CustomerQuery + "/Count";
            this.CustomerQueryReport = this.CustomerQuery + "/Report";
            this.CustomerHistoryQuery = baseApi + "/CustomerHistoryQuery";
        }
        return UrlService;
    })();
    App.UrlService = UrlService;
    angular.module("app").service("UrlService", UrlService);
})(App || (App = {}));
